travis:
  secure:
    BINSTAR_TOKEN: fdodb6SzfamnM3U7hAzfIcv/dgpHWBgZIGqT0M4hUpWqRn1g1AynRebr0JC2AQZ+T0O0Hbjvff0DzcV1xZTt6SVTVNIfka2IBGByEnbvpcvnsaItkvvq6Yt6KPMtqsz3ogDJ3ZwfpOoJjafTGyfQVYjWKduL25NRR7ZhizCb+dm8YxEhkKqkB/cqd7a3n37ragaNIA/+KB5jCGkEH7EqHPj3agIrM0xA0RWswS9NMf6yGJA5aOhM0j898GNfFDNhFA3yajy6smfMsDFwtYC4q6DIK7JmOuYPyKyaFrLs9NziHITYBYCGmJvxZpD/FrhCJ5zRWJJkUhwujWr1fz/uieEWK5ztbbwc3Obizj4zKBlwQf6BCOr3pV4HUcdlDg5vv+g/VrKu47/fZp2L8mXALyRxUQfzj+HGhAPJuQtBkimlM3FyYG8autlte8AI4miYU7E2OBscJAUnnM+sxmJpevtWwKL88gm21KCVBL5mrcGznNSMaPRktLvMpCW1JA5R0TcO1fr8dDgbtDpLK4ai7HsiCrDJqXVM6PjSmWg+tKue1klh1mhn63zFk/4eHmQfhzHoN5BYyN+3xRWBJabGr7OFtzmyDDaY4HpGeFWpw+QbwJucYXRBmx0maJqLqld4lKe9lMUSYy8sqsPqKQAJ60mBbI+2x4/gPhii8T7yKw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
